#--------------------------Backend dev.yml-----------------------------



# name: Backend

# on:
#   push:
#     branches: [develop]
#   pull_request:
#     branches: [develop]  

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   #----------------------------------------Build & Push IMAGE---------------------------------             
#   build-and-push:
#        name: Build and Push Docker Image to ECR
#        runs-on: ubuntu-latest

#        steps:
#          #---------------checkout code--------------------------------------------------------
#          - name: checkout code
#            uses: actions/checkout@v4
#          #--------------------------- Configure AWS credentials-------------------------------
#          - name: Configure AWS credentials
#            uses: aws-actions/Configure-aws-credentials@v4
#            with:
#              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#              aws-region: ${{secrets.AWS_REGION }}

#          # Login to Amazon ECR
#          - name: Login to Amazon ECR
#            id: login-ecr 
#            uses: aws-actions/amazon-ecr-login@v2
#          # -------------------- Backend-----------------
#          - name: Build and Push Backend
#            run: |
#              docker build -t dev-backend .
#              docker tag ${{ secrets.DEV_BACKEND_ECR_REPOSITORY }}:latest ${{ secrets.DEV_BACKEND_ECR_REGISTRY }}:latest
#              docker push ${{ secrets.DEV_BACKEND_ECR_REGISTRY }}:latest


#          #-----------------Deploy to EC2----


#   deploy:

#     runs-on: ubuntu-latest 
#     needs: build-and-push          
#     env:
#       AWS_REGION: ${{ secrets.AWS_REGION }}
#       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

#     steps:

#       - name: Set up SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.DEV_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.DEV_EC2_HOST }} >> ~/.ssh/known_hosts

#       - name: Deploy to EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.DEV_EC2_HOST }} << 'EOF'
#           set -e
#           set -x             

#           # Login to AWS ECR and pull the latest Image
#           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.DEV_BACKEND_ECR_URL }}
#           sudo docker pull ${{ secrets.DEV_BACKEND_ECR_URL }}:latest

#           #Backend-container

#           # Stop and remove the existing container if it exists
#           sudo docker stop backend || true
#           sudo docker rm backend || true

#           # Ensure Docker network exists
#           sudo docker network inspect appnet >/dev/null 2>&1 || sudo docker network create appnet

#           # Run new container without environment variables first
#           sudo docker run -d --name backend -p 5000:5000 --network appnet ${{ secrets.DEV_BACKEND_ECR_URL }}:latest

#           # Create environment file inside EC2
#           cat <<EOT > /home/ubuntu/.env 
#           DEV_SIG_EMAIL=${{ secrets.DEV_SIG_EMAIL }}
#           DEV_FROM_EMAIL=${{ secrets.DEV_FROM_EMAIL }}
#           DEV_SECRET_TOKEN=${{ secrets.DEV_SECRET_TOKEN }}
#           DEV_JWT_KEY=${{ secrets.DEV_JWT_KEY }}
#           DEV_JWT_EXPIRE_IN=${{ secrets.DEV_JWT_EXPIRE_IN }}
#           DEV_MYSQL_HOST=${{ secrets.DEV_MYSQL_HOST }}
#           DEV_MYSQL_DB=${{ secrets.DEV_MYSQL_DB}}
#           DEV_MYSQL_USER=${{ secrets.DEV_MYSQL_USER }}
#           DEV_MYSQL_PASS=${{ secrets.DEV_MYSQL_PASS }}
#           DEV_CLIENT_PORT=${{ secrets.DEV_CLIENT_PORT }}
#           DEV_PORT=${{ secrets.DEV_PORT }}
#           DEV_IP=${{ secrets.DEV_IP }}
#           DEV_URL=${{ secrets.DEV_URL }}
#           DEV_OPENSHIFT_NODEJS_IP=${{ secrets.DEV_OPENSHIFT_NODEJS_IP }}
#           DEV_OPENSHIFT_NODEJS_PORT=${{ secrets.DEV_OPENSHIFT_NODEJS_PORT }}
#           DEV_NODE_ENV=${{ secrets.DEV_NODE_ENV }}


#           NEXT_PUBLIC_API_BASE_URL={{secrets.NEXT_PUBLIC_API_BASE_URL_DEV}}
#           EOT

#           # Copy environment file into the running container
#           sudo docker cp /home/ubuntu/.env backend:/app/.env

#           # Restart the container to load environment variables
#           sudo docker restart backend

#           sudo docker image prune -af
#           EOF
  


# #----------------------------------------End of File-----------------------------------------
















# #--------------------------Frontend dev.yml-----------------------------


# name: frontend-webportal

# on:
#   push:
#     branches: [dev]
#   pull_request:
#     branches: [dev]  

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   #----------------------------------------Build & Push IMAGE---------------------------------             
#   build-and-push:
#        name: Build and Push Docker Image to ECR
#        runs-on: ubuntu-latest

#        steps:
#          #---------------checkout code--------------------------------------------------------
#          - name: checkout code
#            uses: actions/checkout@v4
#          #--------------------------- Configure AWS credentials-------------------------------
#          - name: Configure AWS credentials
#            uses: aws-actions/Configure-aws-credentials@v4
#            with:
#              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#              aws-region: ${{secrets.AWS_REGION }}

#          # Login to Amazon ECR
#          - name: Login to Amazon ECR
#            id: login-ecr 
#            uses: aws-actions/amazon-ecr-login@v2
#          # -------------------- FRONTEND-----------------
#          - name: Build and Push frontend
#            run: |
#              docker build -t dev-pharma .
#              docker build -t dev-pharma .
#              docker tag ${{ secrets.DEV_ECR_REPOSITORY }}:latest ${{ secrets.DEV_ECR_REGISTRY }}:latest
#              docker push ${{ secrets.DEV_ECR_REGISTRY }}:latest
#          #-----------------Deploy to EC2----


#   deploy:

#     runs-on: ubuntu-latest 
#     needs: build-and-push          
#     env:
#       AWS_REGION: ${{ secrets.AWS_REGION }}
#       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

#     steps:

#       - name: Set up SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.DEV_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.DEV_EC2_HOST }} >> ~/.ssh/known_hosts
#       - name: Deploy to EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.DEV_EC2_HOST }} << 'EOF'
#           set -e
#           set -x             
#           # Login to AWS ECR and pull the latest Image
#           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.DEV_ECR_URL }}
#           sudo docker pull ${{ secrets.DEV_ECR_URL }}:latest
#           #FRONTEND-container
#           # Stop and remove the existing container if it exists
#           sudo docker stop frontend || true
#           sudo docker rm frontend || true
#           # Ensure Docker network exists
#           sudo docker network inspect appnet >/dev/null 2>&1 || sudo docker network create appnet
#           # Run new container without environment variables first
#           sudo docker run -d --name frontend -p 3000:3000 --network appnet ${{ secrets.DEV_ECR_URL }}:latest
#           # Create environment file inside EC2
#           cat <<EOT > /home/ubuntu/.env
#           NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
#           NEXT_PUBLIC_IMAGE_BASE=${{ secrets.NEXT_PUBLIC_IMAGE_BASE }}
#           NEXT_PUBLIC_PRODUCT_IMAGE_BASE=${{ secrets.NEXT_PUBLIC_PRODUCT_IMAGE_BASE }}
#           EOT
#           # Copy environment file into the running container
#           sudo docker cp /home/ubuntu/.env frontend:/app/.env
#           # Restart the container to load environment variables
#           sudo docker restart frontend
#           sudo docker image prune -af
#           EOF
  

